<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="surendrasinghgangwar" failures="2" tests="12" name="com.centralvista.test.Ministrymembertest" time="125.377" errors="0" timestamp="2025-09-10T14:58:04 IST" skipped="0">
  <testcase classname="com.centralvista.test.Ministrymembertest" name="valid_registration" time="18.542"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="invalid_registration_existingcontact" time="17.736"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="invalid_registration_existingemail" time="18.164"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="invalid_registration_existingaadhaar" time="23.083"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="minis_mem_list" time="2.919"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="minis_mem_verifyinfo" time="0.583">
    <failure message="Date of Birth mismatch! Expected: 45828.0, Found: 20-06-2025" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Date of Birth mismatch! Expected: 45828.0, Found: 20-06-2025
at com.centralvista.test.Ministrymembertest.validateField(Ministrymembertest.java:353)
at com.centralvista.test.Ministrymembertest.minis_mem_verifyinfo(Ministrymembertest.java:331)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- minis_mem_verifyinfo -->
  <testcase classname="com.centralvista.test.Ministrymembertest" name="minis_mem_uploadfasciawithooufilling" time="0.380"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="minis_mem_uploadfasciainvalidname" time="1.316">
    <failure message="❌ Toast message mismatch! expected [only hindi name is allow] but found [Data captured successfully.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Toast message mismatch! expected [only hindi name is allow] but found [Data captured successfully.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.centralvista.utility.ToastUtil.validateToastMessage(ToastUtil.java:34)
at com.centralvista.test.Ministrymembertest.minis_mem_uploadfasciainvalidname(Ministrymembertest.java:411)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- minis_mem_uploadfasciainvalidname -->
  <testcase classname="com.centralvista.test.Ministrymembertest" name="minis_mem_uploadfascia" time="10.025"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="minis_mem_requestcar" time="13.361"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="minis_mem_requestverify" time="10.131"/>
  <testcase classname="com.centralvista.test.Ministrymembertest" name="minis_mem_logout" time="9.137"/>
</testsuite> <!-- com.centralvista.test.Ministrymembertest -->
